#!/usr/bin/python
import urllib
from bs4 import BeautifulSoup
import re
import sys

url = sys.argv[1]
print url
print "\n\n"

html = urllib.urlopen(url).read()
soup = BeautifulSoup(html)

#debug line for looking a what we are getting:
#print soup.prettify().encode('utf-8')

for script in soup(["script", "style"]):
    script.extract()    # remove style or script stuff
text = soup.get_text() # get the text (ignores html tags)

# break into lines and remove leading and trailing space on each
lines = (line.strip() for line in text.splitlines())
relevant = ""
for line in lines:
  if line: # If it's not blank
    line = re.sub('\s+',' ', line) #reduce all adjacent whitespace characters to just one space character
    if len(line.split(' ')) > 8: # we only want lines with over 5 words
      relevant += line + ' \n'
print relevant.encode('utf-8')
