#!/usr/bin/python
import urllib
from bs4 import BeautifulSoup
import re
import sys

url = sys.argv[1]
print url
print "\n\n"

html = urllib.urlopen(url).read()
soup = BeautifulSoup(html)

find_next_siblings
